# Generated by Django 4.2.3 on 2023-07-27 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_meterrate_electricity_duty'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteredbill',
            name='total_bill',
            field=models.FloatField(default=0),
        ),
    ]
