# Generated by Django 4.2.3 on 2023-07-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_meteredbill_total_bill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteredbill',
            name='total_bill',
            field=models.FloatField(),
        ),
    ]
