# Generated by Django 4.2.3 on 2023-07-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_unmeteredbill_total_bii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unmeteredbill',
            name='total_bii',
            field=models.FloatField(),
        ),
    ]
