# Generated by Django 4.2.3 on 2023-07-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_unmeteredbill_total_bii'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unmeteredbill',
            old_name='total_bii',
            new_name='total_bill',
        ),
    ]
