# Generated by Django 4.2.3 on 2023-07-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_meteredbill_due_date_meteredbill_issued_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteredbill',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='meteredbill',
            name='issued_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='unmeteredbill',
            name='due_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='unmeteredbill',
            name='issued_date',
            field=models.DateField(),
        ),
    ]
