# Generated by Django 4.2.3 on 2023-07-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_meteredbill_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meteredbill',
            name='current_reading',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='meteredbill',
            name='initial_reading',
            field=models.FloatField(default=0),
        ),
    ]
