# Generated by Django 4.2.3 on 2023-07-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_meteredbill_current_reading_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meteredbill',
            old_name='initial_reading',
            new_name='previous_reading',
        ),
    ]
