# Generated by Django 4.2.3 on 2023-07-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_rename_initial_reading_meteredbill_previous_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meteredbill',
            name='current_reading',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='meteredbill',
            name='previous_reading',
            field=models.FloatField(),
        ),
    ]
