# Generated by Django 4.2.3 on 2023-07-31 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0013_alter_meteredbill_current_reading_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="username",
        ),
        migrations.AddField(
            model_name="userdetails",
            name="django_user",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
