# Generated by Django 4.2.3 on 2023-08-04 05:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0015_alter_userdetails_django_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flatrateadditional",
            name="rate",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="flatraterange",
            name="rate",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="flatraterange",
            name="upto",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="meterrate",
            name="electricity_duty",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="meterrate",
            name="fixed_charges",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="meterraterange",
            name="rate",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="meterraterange",
            name="upto",
            field=models.FloatField(),
        ),
    ]
