# Generated by Django 4.2.3 on 2023-08-05 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_flatrate_name_alter_meterrate_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatrate',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='meterrate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
